print ('Hey there!')
print ('What is your name?')
myName = input()
if (myName == "Plopes"):
    print ('How unfortunate...')
else: print ('Nice to meet you, ' + myName)
print ('The lengh of yourr name is: ')
print (len(myName))
print ('What is your age')
age = input()
print ('You will be ' + str(int(age) + 1) + ' in a year!')